--GETDATE()
SELECT GETDATE();

SELECT CONVERT(CHAR, GETDATE(), 103); --Formato dd/mm/yyyy

SELECT DAY(GETDATE()) AS [Dia];
SELECT MONTH(GETDATE()) AS [Mês];
SELECT YEAR(GETDATE()) AS [Ano];
SELECT YEAR('1994-03-24') AS [Ano];

--DATEPART

SELECT DATEPART(YEAR, GETDATE());
SELECT DATEPART(MONTH, GETDATE());
SELECT DATEPART(DAY, GETDATE());

SELECT DATEPART(YEAR, '1994-03-24');

SELECT DATEPART(YEAR, Data_Nascimento) AS [Data de Nascimento] FROM [Paciente];
SELECT DISTINCT DATEPART(YEAR, Data_Nascimento) AS [Data de Nascimento] FROM [Paciente];
SELECT DISTINCT DATEPART(YEAR, Data_Nascimento) AS [Data de Nascimento] FROM [Paciente] ORDER BY 1;

--DATEADD

SELECT DATEADD(YEAR, -2, GETDATE()); -- SUBTRAI DOIS ANOS DA DATA ATUAL
SELECT CONVERT(DATE, DATEADD(YEAR, -2, GETDATE()));

SELECT DATEADD(MONTH, 3, GETDATE()); -- SOMA 3 MESES A DATA ATUAL
SELECT CONVERT(DATE, DATEADD(MONTH, 3, GETDATE()));

SELECT DATEADD(DAY, 28, GETDATE()); -- SOMA 28 DIAS A DATA

SELECT DATEADD(HOUR, 3, GETDATE());

SELECT CONVERT(DATETIME, DATEADD(HOUR, 3, GETDATE()));
SELECT CONVERT(SMALLDATETIME, DATEADD(HOUR, 3, GETDATE()));

SELECT CONVERT(DATETIME, DATEADD(HOUR, 3, GETDATE())) AS DateT,
        CONVERT(SMALLDATETIME, DATEADD(HOUR, 3, GETDATE())) AS SmallD

--DATEDIFF

SELECT DATEDIFF(YEAR, GETDATE(), DATEADD(YEAR, 4, GETDATE())) AS [Anos];
SELECT DATEDIFF(MONTH, GETDATE(), DATEADD(YEAR, 2, GETDATE())) AS [Meses];
SELECT DATEDIFF(DAY, GETDATE(), DATEADD(YEAR, 3, GETDATE())) AS [Dias];

SELECT DATEDIFF(HOUR, '1994-03-24', GETDATE()) AS [Horas de vida];
SELECT DATEDIFF(MINUTE, '1994-03-24', GETDATE()) AS [Minutos de vida];
SELECT DATEDIFF(SECOND, '1994-03-24', GETDATE()) AS [Segundos de vida];